FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm ci

COPY . .

RUN npx prisma generate
RUN npm run build
RUN npx tsc prisma/seed.ts --target es2022 --module commonjs --moduleResolution node --esModuleInterop --outDir dist/prisma

# ===============================

FROM node:22-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY package*.json ./
COPY prisma ./prisma/
COPY public ./public

RUN npm pkg delete scripts.prepare

RUN npm ci --omit=dev

RUN npm cache clean --force

RUN npx prisma generate

COPY --from=builder /app/dist ./dist

RUN addgroup -S nodejs && \
    adduser -S nestjs -G nodejs

RUN mkdir -p \
    /app/public/uploads/products \
    /app/public/uploads/delivery-proofs \
    /app/public/uploads/seller-shipments

RUN chown -R nestjs:nodejs /app

USER nestjs

EXPOSE 4000

CMD ["node","dist/main.js"]